Module Doors
    Friend ReadOnly LeftDoor As New List(Of String) From {
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX",
            "              ",
            "    XXX       ",
            "    X  XX     ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X  XX",
            "    X    XXX  ",
            "    X         ",
            "    X         ",
            "    X         ",
            "  XX          ",
            "XX            "
        }
    Friend ReadOnly AheadDoor As New List(Of String) From {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                          X",
            "X                          X",
            "X                          X",
            "X       XXXXXXXXXXXX       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "X       X          X       X",
            "XXXXXXXXX          XXXXXXXXX",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        }
    Friend ReadOnly RightDoor As New List(Of String) From {
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            ",
            "              ",
            "       XXX    ",
            "     XX  X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "    X    X    ",
            "XX  X    X    ",
            "  XXX    X    ",
            "         X    ",
            "         X    ",
            "         X    ",
            "          XX  ",
            "            XX"
        }
    Friend ReadOnly AllDoors As New List(Of String) From {
        "XX                                                    XX",
        "  XX                                                XX  ",
        "    XX                                            XX    ",
        "      XX                                        XX      ",
        "        XX                                    XX        ",
        "          XX                                XX          ",
        "            XX                            XX            ",
        "              XXXXXXXXXXXXXXXXXXXXXXXXXXXX              ",
        "    XXX       X                          X       XXX    ",
        "    X  XX     X                          X     XX  X    ",
        "    X    X    X                          X    X    X    ",
        "    X    X    X       XXXXXXXXXXXX       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    X       X          X       X    X    X    ",
        "    X    X    XXXXXXXXX          XXXXXXXXX    X    X    ",
        "    X    X  XX                            XX  X    X    ",
        "    X    XXX                                XXX    X    ",
        "    X                                              X    ",
        "    X                                              X    ",
        "    X                                              X    ",
        "  XX                                                XX  ",
        "XX                                                    XX"
        }
End Module
