Module Walls
    Friend ReadOnly LeftWall As New List(Of String) From {
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            "
        }
    Friend ReadOnly AheadWall As New List(Of String) From {
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "X                          X",
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            ",
            "                            "
        }
    Friend ReadOnly RightWall As New List(Of String) From {
            "            XX",
            "          XX  ",
            "        XX    ",
            "      XX      ",
            "    XX        ",
            "  XX          ",
            "XX            ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "              ",
            "XX            ",
            "  XX          ",
            "    XX        ",
            "      XX      ",
            "        XX    ",
            "          XX  ",
            "            XX"
        }
    Friend ReadOnly AllWalls As New List(Of String) From {
        "XX                                                    XX",
        "  XX                                                XX  ",
        "    XX                                            XX    ",
        "      XX                                        XX      ",
        "        XX                                    XX        ",
        "          XX                                XX          ",
        "            XX                            XX            ",
        "              XXXXXXXXXXXXXXXXXXXXXXXXXXXX              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              X                          X              ",
        "              XXXXXXXXXXXXXXXXXXXXXXXXXXXX              ",
        "            XX                            XX            ",
        "          XX                                XX          ",
        "        XX                                    XX        ",
        "      XX                                        XX      ",
        "    XX                                            XX    ",
        "  XX                                                XX  ",
        "XX                                                    XX"
        }
End Module
